import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Link href="/dashboard" className="underline">
          Dashboard
        </Link>
        &nbsp;|&nbsp;
        <Link href="/about" className="underline" prefetch={false}>
          About
        </Link>
        &nbsp;|&nbsp;
        <Link href="/todo-list" className="underline" prefetch={false}>
          Todo List
        </Link>
      </body>
    </html>
  );
}
